# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53416622da7d9e793a81fadf9face1a14c583335b118c63c984669f045f79af58d682e2695077d22a544bf6ea0e9aa75a8b131d53a106582d96a150b0ff0ed31

test:
  secret_key_base: 03a28e3a722d0242b540b89c9e94539906dc4349361998eddf6f045d56868bd7d78ecc5e3d9b1a94c840f15cc76f67e7379e17630080ece19e7b980fae83aa77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
